import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'notyf/notyf.min.css';
import { headers } from 'next/headers';
import { Provider } from '../helpers/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider headers={headers()}>{children}</Provider>
      </body>
    </html>
  );
}
